### ISSUE TITLE
Helicopter (and maybe plane) repair sequence improvements

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#318]
> I think that good idea could be that u need find a special things to repair a chopper or plane like engines and stuff like that. becouse i think Whentch, Screwdriver, Hammer, Wrentch and refuel is to easy to get something for flying.
- Posted 14 June 2014

I added a Gyroscope item specifically for this but never implemented it!

Helicopters should be special though, they are extremely valuable vehicles and should require some more work to repair fully.

I'll flesh this idea out more in time but it's definitely something for the next development phase.

**Comment by NegativeIQ** [comment]
That is good idea, maybe add kerosene as aircraft fuel and make it very hard to get so players with aircraft dont scout non stop for their team mates. And if normal vehicle fuel (gasoline) is added instead of kerosene, every few seconds check and randomly (with about 5% chance) turn off engine for a second or two so that its not safe to fly those things on normal fuel. 

Maybe make it possible to increase fuel quality to kerosene with crafting ??? A bit stupid idea but it still has some sense... ( I think :smile: )

**Comment by Southclaw** [comment]
Yeah I've had that in consideration for a long time too! (almost as long as the Gyroscope). It will be called Avgas (aviation gasoline) since Kerosene is for jet-turbines (though I may add that too for larger turbine based helicopters such as the Cargobob and Lev').

I won't make it craftable though, partly for realism and partly to drive players to visit airports to get Avgas in order to add another risk factor to owning a helicopter.
