### ISSUE TITLE
Bar

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#340]
How do I use this bar?
![bar1](https://cloud.githubusercontent.com/assets/24555369/21472267/cffe8d70-cab7-11e6-935e-008d2f270ecb.JPG)

**Comment by Southclaws** [comment]
"Issues" are for _bug reports_ and tracking _new features_ not questions.
Either use dc.southcla.ws or hello@southcla.ws, you'll have to elaborate though because I don't really understand what you mean. That bar is the old hunger bar from a **very** old version of the gamemode (that I don't recommend using at all).
