### ISSUE TITLE
Wrong playertext when opening a trunk

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#348]
"Door locked must use crowbar"...

I found the car with it's trunk open but the rest of the doors are locked. When I open and close the trunk it displays that playertext.

![sa-mp-000](https://cloud.githubusercontent.com/assets/1616657/21486063/557d46e2-cba5-11e6-907b-c9fa59b41b96.png)

**Comment by Southclaws** [comment]
I think that's because when you hit F it triggeres the clientside enter vehicle code regardless of whether you're at the trunk or not.

However, I may still be able to fix this by checking the angle from the vehicle to the player (same as the trunk check) and disable this message if the player is at the back.
