### ISSUE TITLE
Incorrect height for workbench

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#351]
![sa-mp-003](https://cloud.githubusercontent.com/assets/1616657/21486204/ff4e651e-cba7-11e6-8b85-9dda32d931c1.png)

**Comment by Southclaws** [comment]
These are all the pre-placed workbenches in `/world/zones/`and this happened because I changed from `CreateWorkbench` to `CreateItem(item_Workbench, ...` and the item offset came into effect. There aren't many workbenches though so it should be a simple job of just subtracting 0.5m from each item's Z coordinate.
