### ISSUE TITLE
Incorrect arrow offset when building a wood ramp

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#353]
![sa-mp-006](https://cloud.githubusercontent.com/assets/1616657/21486302/0dc641e6-cbaa-11e6-9580-72f4528f816a.png)
![sa-mp-007](https://cloud.githubusercontent.com/assets/1616657/21486301/0dc37682-cbaa-11e6-9b6a-2eb808a99adb.png)
![sa-mp-008](https://cloud.githubusercontent.com/assets/1616657/21486300/0dc2f2a2-cbaa-11e6-812b-2c3aa7b407eb.png)

**Comment by Southclaws** [comment]
I've always wanted to remove that ramp, it causes me so many problems because of the awkward angle...

I'll try and fix this one but no promises. I may just make the ramp into a craft-construct item only not a defence, and make it so it is always a ramp rather than a wall. Then players can still use it as a bridge/jump ramp but it doesn't have to cause issues as a defence wall with it's awkward 25 degree rotation offset...

**Comment by viruxe** [comment]
Removing it as a defence might cause some consirn because it's one of the defences that has most coverage. It's very sought after.
It has an awkward angle but players have always managed to deal with it.

**Comment by Southclaws** [comment]
I've always managed to do the defence code without the need to touch matrix translations but I may have to for this one... I see what you mean though, players do love a good wood ramp.

**Comment by viruxe** [comment]
If this is an issue just for the wood ramp we might aswell just leave it like that. It's not that big of an issue.

**Comment by Southclaws** [comment]
Confirmed, it's an issue for most defences. I'll rewrite the angle arithmetic for the arrow object.

**Comment by Southclaws** [comment]
I've fixed this for everything including the wood ramp now, and the wood ramp is still a defence.
