### ISSUE TITLE
Endurance skill has too much effect on jumping 

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#360]
Formula needs a rework.

**Comment by NegativeIQ** [comment]
Player velocity in samp is very tricky thing, here are some ideas for workarounds if you dont manage to get formula working...
1. Ignore Z velocity if you didnt already
2. Instead of setting players velocity replace running animations and control their speed?
3. Instead of allowing player to run faster (velocity or anim), allow him to run "longer" by again using anims?
4. Endurance doesnt have to be running, maybe disallow players to carry some heavy objects for longer time if they dont have enough endurance?
