### ISSUE TITLE
Lockers can't be crowbared

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#423]
Right now it opens the inventory instead of starting the crowbar process when you have the crowbar in hand.

**Comment by Southclaws** [comment]
I've wanted to address this interaction issue for a while. No items can be used to interact with Safebox items currently because it just triggers the dialog to show.

So, one solution would be to split interaction across "Tap" and "Hold" like how when you're not holding anything, you tap to open and hold to pick up.

In this scenario, the player would hold the interact key with a Crowbar in-hand and it wouldn't trigger the dialog.

This may require some SIF changes though. But once this is done, I'd like to give players the ability to modify Safebox items by adding names, installing locks, etc.
