### ISSUE TITLE
Death in vehicle

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#471]
When a player ejects another from the vehicle, he dies.
Why does this happen sometimes?

**Comment by NegativeIQ** [comment]
Samp bug, its known to happen allot on DayZ servers, pretty sure it has to do something with objects being attached to player.

**Comment by Southclaws** [comment]
It used to happen before object attachments were around, unfortunately it's never been fixed.

There is an attempt at fixing it that works most of the time but latency has proven it a difficult problem to solve fully. It's also difficult to test with all the factors at play.

Maybe once the codebase is stable in the coming months I'll take a look at refining the existing fix.

**Comment by Y-Less** [comment]
https://github.com/Open-GTO/sa-mp-fixes/issues/31

If you have some ideas, maybe we could combine efforts?

**Comment by Southclaws** [comment]
Sounds good! I'll try and find the code that sort of fixed it...

**Comment by Southclaws** [comment]
https://github.com/Southclaws/ScavengeSurvive/blob/87b7eac76c4566a8d30cf791fa191d9c66fee2ae/gamemodes/sss/core/vehicle/anti-ninja.pwn

It seems like my solution was to kick the player out if they hit a key while entering a vehicle, however looking at the code now I can see how this could be circumvented.

But I think the idea behind this code was to favour the carjacker rather than the victim - if a player gets into a position where they can enter the vehicle, they deserve to actually get the vehicle and not get teleported out because they happen to be accidentally pressing the spacebar. So the idea here was to teleport out the driver instead.

**Comment by KoloradoPlay** [comment]
I Did it:
`#include <YSI\y_hooks>

#include <OnPlayerJackVehicle>

/*
	Anti "ninja-jack" (or anj)
*/

public OnPlayerJackVehicle(playerid,victimid,vehicleid,bool:ninjajack)
{
	if(ninjajack == true)
	{
	    new
			Float:x,
			Float:y,
			Float:z;
			
		GetPlayerPos(playerid, x, y, z);
        SetPlayerPos(targetid, x, y, z);
		printf("Player %d tentando fazer ninja-jack", playerid);
	}
	return 1;
}`

**Comment by KoloradoPlay** [comment]
I only managed to solve this by removing the anti-ninja.pwn

**Comment by NexiusTailer** [comment]
Another variant of fix: http://pastebin.com/mFSpAVJa
