### ISSUE TITLE
Anti Ninja Fix

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#480]
I found a solution for the ninja jack, I tested it and it worked 100%.

The code is:

```
hook OnPlayerStateChange(playerid,newstate,oldstate)
{
    if ( oldstate == PLAYER_STATE_DRIVER && newstate == PLAYER_STATE_ONFOOT ) 
    {
        ClearAnimations(playerid);
    }
}
```

**Comment by Southclaws** [comment]
This used to be the solution in game but with hundreds of players a month entering vehicles, it proved to be not 100% working. It also favours the driver rather than the hijacker which is something I talked about in the other thread.

Thanks for the contribution though, I may add it under a setting flag to switch between different mitigation methods.
