### ISSUE TITLE
Report: problem in compilation

### ISSUE THREAD

**Issue by MBaltz** [Southclaws/ScavengeSurvive#516]
## Hello, Southclaws.
__I'm here to report a error at the build stage__

---
* Branch: Master
(last commit: 64adf18b09d04618f7572e7c0f3eea8db43e69bf)
(las commit date:   Mon Oct 19 23:01:51 2020 +0100)
* Pawn compiler 3.10.10
(build in my computer)
* SO: linux-64

command:  __sampctl p ensure --verbose__
[ensure_output.txt](https://github.com/Southclaws/ScavengeSurvive/files/5417055/ensure_output.txt)

command: __sampctl p build --verbose__
[build_output.txt](https://github.com/Southclaws/ScavengeSurvive/files/5417006/output.txt)

**Comment by MBaltz** [comment]
__In ensure_output we have WARNs, but I think it isn't the reason of the compilation error__

**Comment by Southclaws** [comment]
Hi, master branch was a little broken for a bit due to some changes to SIF - I added tags while migrating to the new libraries.

Master branch now builds:

https://github.com/Southclaws/ScavengeSurvive/runs/1290007108?check_suite_focus=true

This should be a one-time thing though now everything is migrated! Let me know if you run into more issues.

**Comment by MBaltz** [comment]
Okay!
Thank you for your return.
